export const aggravatedAssaults = [
  {
    value: 205,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 740,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1025,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1012,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1527,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1567,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1517,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1502,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2034,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2574,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2731,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2742,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2915,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3011,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3452,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3344,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3282,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3240,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3185,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3393,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3408,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3112,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3579,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3839,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3660,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3786,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3954,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const burglaries = [
  {
    value: 1004,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 4041,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 4920,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5156,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6751,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6665,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6914,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7029,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 9457,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 13164,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 13378,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 12243,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 12777,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 13316,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 15436,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 14714,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 15359,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 14987,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 12769,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 13249,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 13728,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 11336,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 12630,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 12782,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 11347,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 9700,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 8497,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const larcenies = [
  {
    value: 4455,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 19230,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 27312,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 26603,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 33666,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 35387,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 37104,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 36843,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 48009,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 62558,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 59901,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 59563,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 58745,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 55095,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 59308,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 61103,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 60426,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 58681,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 56551,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 59224,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 59916,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 58143,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 61386,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 60720,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 56658,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 49296,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 47241,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];
export const motorVehicleThefts = [
  {
    value: 312,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1272,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1727,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1871,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2566,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2878,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3404,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3090,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 4824,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7078,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6769,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6789,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7758,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7791,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 8737,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7174,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6650,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5826,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6127,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5962,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7385,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6974,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 8613,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 9209,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 9105,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 7319,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6452,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const homicides = [
  {
    value: 12,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 15,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 27,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 15,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 30,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 26,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 23,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 31,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 56,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 36,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 49,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 41,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 45,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 46,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 52,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 36,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 33,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 47,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 45,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 47,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 40,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 62,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 50,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 71,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 63,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 58,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 64,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const rapes = [
  {
    value: 98,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 286,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 373,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 388,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 555,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 564,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 662,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 748,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 896,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1105,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1171,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1201,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1171,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1178,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1274,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1232,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1167,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1208,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1237,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1377,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1389,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1380,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1513,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1422,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1589,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1604,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1566,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const robberies = [
  {
    value: 34,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 137,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 169,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 167,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 310,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 405,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 378,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 383,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 792,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 990,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1106,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1051,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 917,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1104,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1345,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1336,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1205,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1187,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1033,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1022,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1191,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1222,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1281,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1471,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1357,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1150,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1051,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const arsons = [
  {
    value: 49,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 153,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 166,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 194,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 193,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 212,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 205,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 259,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 329,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 346,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 298,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 247,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 298,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 347,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 315,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 283,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 304,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 252,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 231,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 241,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 213,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 266,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 202,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 220,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 185,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 157,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 173,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];
export const violentCrimes = [
  {
    value: 349,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1178,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1594,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 1582,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2422,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2562,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2580,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 2664,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 3778,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 4705,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5057,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5035,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5048,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5339,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6123,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5948,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5687,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5682,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5500,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5839,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6028,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 5776,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6423,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6803,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6669,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6598,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 6635,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];

export const propertyCrimes = [
  {
    value: 5820,
    data_year: 1993,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 24696,
    data_year: 1994,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 34125,
    data_year: 1995,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 33824,
    data_year: 1996,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 43176,
    data_year: 1997,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 45142,
    data_year: 1998,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 47627,
    data_year: 1999,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 47221,
    data_year: 2000,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 62619,
    data_year: 2001,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 83146,
    data_year: 2002,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 80346,
    data_year: 2003,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 78842,
    data_year: 2004,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 79578,
    data_year: 2005,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 76549,
    data_year: 2006,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 83796,
    data_year: 2007,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 83274,
    data_year: 2008,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 82739,
    data_year: 2009,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 79746,
    data_year: 2010,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 75678,
    data_year: 2011,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 78676,
    data_year: 2012,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 81242,
    data_year: 2013,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 76719,
    data_year: 2014,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 82831,
    data_year: 2015,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 82931,
    data_year: 2016,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 77295,
    data_year: 2017,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 66472,
    data_year: 2018,
    month_num: 0,
    key: "Offense Count",
  },
  {
    value: 62363,
    data_year: 2019,
    month_num: 0,
    key: "Offense Count",
  },
];
